# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sagara Paranagama
tagline: 'Math, CS & ML'
description: |
    This is Sagara Paranagama.
    He is a Software Engineer.
    He shares his thoughts on topics that he likes: CS, Math and Machine Learning.
    Sagara is nice.
    Be like Sagara.
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
paginate:            5
twitter_username: SParanagama
github_username:  SParanagama

# About/contact
author:
  name:              Sagara Paranagama
  url:               https://twitter.com/SParanagama
  email:             sagara89 *at* gmail

# Custom vars
version:             1.0.0

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true


# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax

# Gems
gems: [jekyll-paginate]
